version: '3.3'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb_container
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    networks:
      - app-db
networks:
  app-db:
    driver: bridge
volumes:
  influxdb-storage:

